### ISSUE TITLE
Cannot read property 'previous' of undefined

### ISSUE THREAD

**Issue by EloyRoura** [SalmanMujtaba/Angular-Email-App#1]
Hello,

I am pretty new with angular and totally unaware about firebase. I just created the accounts all around, and follow all the instructions installing all packages and make it compile okay. Now I see the actions in the console of my firebase, but still the message is not getting through.

This is the error message:

> TypeError: Cannot read property 'previous' of undefined
>     at exports.sendContactMessage.functions.database.ref.onWrite.event (/user_code/index.js:15:15)
>     at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
>     at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
>     at /var/tmp/worker/worker.js:730:24
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

together with a previous message, also not very comforting:

> Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions

Any hint on that would be awesome!

Thanks in advance,
Eloy

**Comment by SalmanMujtaba** [comment]
Hi, I'm sorry for the super late reply, but what firebase account are you using?
